mqtt:
  host: 172.16.2.122
  port: 1883
  client_id: growatt_mqtt
  base_topic: growatt
  autodiscover_prefix: homeassistant

inverter:
  inverter_name: growatt_4000tl
  inverter_model: Growatt 4000TL Inverter

modbus:
  method: rtu
  port: /dev/ttyUSB0
  stopbits: 1
  bytesize: 8
  parity: N
  baudrate: 9600
  timeout: 1

update_interval: 5
offline_wait_interval: 60
error_interval: 60